** Table

|----------------------+---------------------------------------------------------------------|
| Name                 | LinkedIn URL                                                        |
|----------------------+---------------------------------------------------------------------|
| Angelia Davis        | https://LinkedIn.com/in/angelia-davis/                              |
| Cesar Partida        | https://LinkedIn.com/in/cesar-partida-pmbilingualprojectmanagement/ |
| Craig Oliver         | https://LinkedIn.com/in/craigpoliver/                               |
| Cris Casey           | https://LinkedIn.com/in/criscasey/                                  |
| George Churchwell    | https://LinkedIn.com/in/georgechurchwell-6a6a/                      |
| Gil Pizano           | https://LinkedIn.com/in/gilpizano                                   |
| Janet Perez          | https://LinkedIn.com/in/janetperez4/                                |
| Jeff Justiz          | https://LinkedIn.com/in/jjustiz/                                    |
| Jesse Morgan         | https://LinkedIn.com/in/jesse-g-morgan                              |
| John Ruppel          | https://LinkedIn.com/in/johnruppel/                                 |
| Jonathan Mickles     | http://LinkedIn.com/gr8fulbishop                                    |
| Jonathan Stephens    | https://LinkedIn.com/in/elnatnal                                    |
| Julia Taylor         | https://LinkedIn.com/in/juliataylorcpc/                             |
| Kara Flanagan        | https://LinkedIn.com/in/karaflanagan/                               |
| Krista Roes          | https://LinkedIn.com/in/kristaroes                                  |
| LaVern Witherspoon   | https://LinkedIn.com/in/lavernowitherspoon                          |
| Lakievia Johnson     | https://LinkedIn.com/in/lakieviajohnson                             |
| Laura Brandenburg    | https://LinkedIn.com/in/laurabrandenburg/                           |
| Michael Wolf         | https://LinkedIn.com/in/MRWolf                                      |
| Nakoya Solomon       | https://LinkedIn.com/in/nakoya-solomon-63b603a5                     |
| Robby Boys           | https://LinkedIn.com/in/robby-boys-pmpb7820566/                     |
| Romona Benson        | https://LinkedIn.com/in/romona-benson                               |
| Russell Blackburn    | https://LinkedIn.com/in/russ-blackburn-maolpmp-70159812             |
| Sam Slater           | https://LinkedIn.com/in/samanthaconlynslater/                       |
| Srinath Kondabathini | https://LinkedIn.com/in/srinath-k-852362a/                          |
|----------------------+---------------------------------------------------------------------|


** Text

00:45:59 Russell Blackburn: www.linkedin.com/in/russ-blackburn-maolpmp- 70159812
00:46:20 Michael Wolf: EST - Michigan, New York, Florida - Technomad - https://LinkedIn.com/in/MRWolf
00:47:52 Laura Brandenburg: Happy to connect with you all on LinkedIn: https://www.linkedin.com/in/laurabrandenburg/
00:48:44 Craig Oliver: Happy to connect! https://www.linkedin.com/in/craigpoliver/
00:48:53 Srinath Kondabathini: https://www.linkedin.com/in/srinath-k- 852362a/
00:50:01 Jesse Morgan: linkedin.com/in/jesse-g-morgan Hi everyone, I am currently looking for a new opportunity
00:50:15 Julia Taylor: I've already attempted to connect with some of you, lol, but my linkedin is https://www.linkedin.com/in/juliataylorcpc/
00:50:16 Cesar Partida | Seeking new opportunities!: https://www.linkedin.com/in/cesar-partida-pmbilingualprojectmanagement/
00:50:20 LaVern Witherspoon - IIBA RTP Marketing: https://www.linkedin.com/in/lavernowitherspoon
00:50:32 Sam Slater: https://www.linkedin.com/in/samanthaconlynslater/
00:50:34 Romona Benson: https://www.linkedin.com/in/romona-benson #OpentoWork
00:50:56 Nakoya Solomon: https://www.linkedin.com/in/nakoya-solomon- 63b603a5
00:51:05 Robby Boys: https://www.linkedin.com/in/robby-boys-pmpb7820566/
00:51:37 Srinath Kondabathini: I am working for a federal contractor at Vienna, VA, I am looking for a new job. I am Scrum Master/ Project & Porgram Manager - https://www.linkedin.com/in/srinath-k-852362a/
00:51:40 Angelia Davis: Good morning, from South Carolina...https://www.linkedin.com/in/angelia-davis/
00:51:50 Jonathan Stephens (he/him): <3 woo! https://linkedin.com/in/elnatnal Open for work as well
00:52:14 Jeff Justiz: Hi from Toronto and open for work: https://www.linkedin.com/in/jjustiz/
00:52:35 Jonathan Mickles: Good morning everyone. Looking for a seasoned Program Manager as a mentor. http://LinkedIn.com/gr8fulbishop. Also open to a PM position/networking in the AI, real estate and/or block chain technologies
00:54:22 Lakievia "Lucky" Johnson, She/Her - Eastern Time:Connect with me on LinkedIn: https://www.linkedin.com/in/lakieviajohnson?utm_source=share&utm_campaign =share_via&utm_content=profile&utm_medium=android_app
00:54:23 Janet Perez: Happy to connect: https://www.linkedin.com/in/janetperez4/
00:54:44 Gil Pizano: https://www.linkedin.com/in/gilpizano Glad to connect with people! Good morning from Richmond, VA!
00:56:57 Srinath Kondabathini: I am working for a federal contractor at Vienna, VA, I am looking for a new job. I am Scrum Master/ Project & Porgram Manager - https://www.linkedin.com/in/srinath-k-852362a/
01:00:03 Jonathan Mickles: I also can refer Cyber professionals to positions. There are several open. Feel free to connect http://LinkedIn.com/gr8fulbishop
01:03:39 John Ruppel: https://www.linkedin.com/in/johnruppel/ My passion is to help people and their organizations be successful with, and teach leaders how to successfully lead their GenAI, Prescriptive AI, AI, Agile, DevOps adoptions/transformations, Digital/Business Transformations… simply put their change initiatives... Feel free to reach out if I can be of help... Looking forward to having a conversation and the opportunity to help you on your change journey
01:07:44 Cesar Partida | Seeking new opportunities!: I'm happy to connect and look for new opportunities you currently work in! https://www.linkedin.com/in/cesar-partida-pm-bilingualprojectmanagement/
01:12:03 Krista Roes: www.linkedin.com/in/kristaroes
01:15:06 George Churchwell: https://www.linkedin.com/in/georgechurchwell- 6a6a/
02:03:37 Kara Flanagan: Hi Everyone! Glad to be here and looking forward to connecting and learning today. Connect with me on LinkedIn at https://www.linkedin.com/in/karaflanagan/
02:04:18 Gil Pizano: Glad to connect and help people connect with others https://www.linkedin.com/in/gilpizano
02:07:51 Jonathan Mickles: Hey everyone. Happy to connect. Looking for a sounding board / mentor who is a seasoned Program Manager. http://LinkedIn.com/gr8fulbishop #AI #Blockchain #RealEstate #Cybersecurity
02:30:19 Kara Flanagan: I LOVE all of the knowledge sharing in the chat and expertise on this event! If anyone is interested in sharing and teaching, please connect with me. We are ALWAYS looking for contract instructors. https://www.linkedin.com/in/karaflanagan/
01:43:10 Michael Wolf: Replying to "Another graphic prom..." If you're interested in details, contact me at MichaelRWolf@att.net or https://LinkedIn.com/in/MRWolf
00:39:15 Jonathan Stephens (he/him): Connect on LinkedIn: https://linkedin.com/in/elnatnal Read on Substack: https://jonathanstephens.substack.com Book time on my calendar: https://cal.com/jonathanstephens/gen-ai-day-4
00:57:05 Kara Flanagan: Replying to "Here is a list for a..." https://www.linkedin.com/in/karaflanagan/
01:21:38 Craig Oliver: Insightful and a perspective often not heard thank you! Happy to connect to keep tht discussions going: https://www.linkedin.com/in/craigpoliver/
01:25:39 John Ruppel: https://www.linkedin.com/in/johnruppel/
01:59:02 Michael Wolf: Before everyone drops... I'm happy to connect afterwards on LinkedIn or a virtual coffee -- https://LinkedIn.com/in/MRWolf or MichaelRWolf@att.net
02:02:43 Cris Casey: Would love to connect - >https://www.linkedin.com/in/criscasey/
02:10:46 John Ruppel: Hope everyone had a good time today... if you have a need for GenAI, Prescriptive AI, AI adoption or helping, teaching leaders how to lead a successful adoption, I am here to help... welcome any conversations or please reach out if I can be of help https://www.linkedin.com/in/johnruppel/
02:13:35 Kara Flanagan: Great sessions today and great to meet everyone. AI Certs was happy to be part of this event! Kara@aicerts.ai https://www.linkedin.com/in/karaflanagan/ www.aicerts.ai/certifications Discount Code: GENAI20
