* People

<2025-03-27 Thu> 


Dana Dorroh
LinkedIn: https://www.linkedin.com/in/onesourcenc/
Company: One Source of NC

Julio Fernandez
LinkedIn: https://www.linkedin.com/in/socialjulio/

Lara Hill
LinkedIn: https://www.linkedin.com/in/larahill/

Marc Balcer
LinkedIn: https://www.linkedin.com/in/marcbalcer/

Mark Lane
LinkedIn: https://www.linkedin.com/in/mark-lane-phd/

Andy Cooper
LinkedIn: https://www.linkedin.com/in/andy766cooper/


George Churchwell
LinkedIn: https://www.linkedin.com/in/george-churchwell-6a6a/
Company: Mt Tam Innovations

* Companies

Skills Development Group - https://www.linkedin.com/company/skills-development-group/


* Links

https://skills-group-org.zoom.us/w/89164598453?tk=Mzqvr9C88qkhkgMN9qtI6G74YD9hZT95-_2GoNXf6s8.DQcAAAAUwp_MtRZfRWpvendNMVNPeU5QNURlMTRWYjF3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&pwd=nS5bTa0h38ziwxA9I7RvY3TszrqNAg.1

https://skillsdg.com/us/learning-hub/webinars/go-beyond-chat-gpt-with-ai-agents-sell-more-market-smarter-and-support-better

https://www.icloud.com/notes/note/UHJpdmF0ZTo6Tm90ZXM6OmN1cnJlbnRVc2VyOjozQ0I5NDlBQi1BNzQ3LTRBOUItQTFEOS0xQ0NBOTY0M0Y3MTY=

https://skills-group-org.zoom.us/w/89164598453?tk=Mzqvr9C88qkhkgMN9qtI6G74YD9hZT95-_2GoNXf6s8.DQcAAAAUwp_MtRZfRWpvendNMVNPeU5QNURlMTRWYjF3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&pwd=nS5bTa0h38ziwxA9I7RvY3TszrqNAg.1




* Sessions

** Session 1 - 9:30 - Chris Knott
https://www.linkedin.com/in/chris-knotts/
Skills Development Group
Raleigh NC


Quote: "Amazing how fast the wallets will open".

** Session 2 - 10:00 - Laura Mahalel 
https://www.linkedin.com/in/LauraCaneMahalel/
Company: #OpenToWork


Say: Ma Ha Lel

Technical Educator in FinTech.  NYC.  Jersey City.

Was laid off about a year ago.  May connect on state of training for future.

** Session 3 - Julio Fernandez
LinkedIn: https://LinkedIn.com/in/socialJulio 
Company: Cisco
email: julio@socialJulio.com
Location: St George UT


Very open to networking.  Very open personality.  Great top-10 list.

** Session 4 - Kenya Oduor
Company: Mt Tam Innovation
Locaiton: Raleigh-Durham-Chapel Hill NC
LinkedIn: https://www.linkedin.com/in/kenyaoduor/

Was open and facilitating in her session.

Video.  LinkedIn contacts.  High EQ.

See: Lean Geeks
    See: Dana Dorroh, One Source of NC
    https://www.linkedin.com/in/onesourcenc/    



*** LinkedIn posting

https://www.linkedin.com/posts/kenyaoduor_usercentereddesign-humancentereddesign-customerexperience-activity-7285670920180883457-8a78?utm_source=share&utm_medium=member_desktop&rcm=ACoAAAADxzIBUUakc3o7MptwunFkY9GeiKZrIN8


```text Hear! Hear! I, too, got trapped in Dropbox's "information
hiding upsell". If they were (malevolently) thinking "Hah! Once they
get here, ther's no way out", they were deceived. I am out. It wasn't
an up-sell, it was an out-sell.

Because I have a passion for #UX (User eXperience), and a sense that I
am a partner with the teams that develop the tools I use, my first
instinct was to share my experience and suggest an improvement.
```






Having a passion for #UX (User eXperience) and a desire to become a partner with the teams that develop tools I use.


, I almost wrote them a suggestion that they improve their flow, but then I realized that the flow wasn't (mere excusable) ignorance (of my experience), but worse... it was (unexcusable) malevolence by limiting my freedom to choose my experience.



Aside -- I see that your profile highlights NN/g 



P.S.  I see that you've highlighted NN/g.  Nice!  I've followed them for decades now.  And... just to counter-balance your bad Dropbox experience, I'd like to point out the well-done experience of reading their newsletter.  I have always had the feeling that they valued what's most important to me -- my time and focus -- by providing multiple levels of engagement for me that _I_ can choose.  Yes, NN/g "signposts" the various ways I can engage their content (versus Dropbox giving us only 1 choice -- their choice).



For example, when I receive their newsletter, depending on my day, I can invest:

 3 seconds by reading the well-distilled Subject to get an industry buzz alert

20 seconds by reading the (again, well-distilled) 3 sentence summary that is well placed at the top of the article

more time -- and they estimate that UP FRONT for me -- to read the whole article



Their newsletters are always wonderful, but I don't always have the time to read them, so it's great that they give me "signposts" so that I can direct my most important resources -- time and focus -- at a level that _I_ choose (with their support).

** Session 5 - Dr Mark Lane
Company: Cisco
Location: Tampa FL
LinkedIn: https://www.linkedin.com/in/mark-lane-phd/

** Session - 1:00 - Zaki Medina

LinkedIn: https://www.linkedin.com/in/zakimedina/

<2025-05-21 Wed> Course -- https://skillsdg.com/us/learning-hub/webinars/go-beyond-chat-gpt-with-ai-agents-sell-more-market-smarter-and-support-better



** Session - Jessica Katz
LinkedIn: https://www.linkedin.com/in/jeskatz/
Company: #OpenToWork
Company: PolyLabor

** Session - 2:00 - Omer Hashmi

** Session - George Churchwell
https://www.linkedin.com/in/george-churchwell-6a6a/


** 4:00 Session - Andy Cooper
Skils Development Group
Wellington New Zealand
https://www.linkedin.com/in/andy766cooper/

Story about running out of tokens while exploring a problem with an ELT member
Q: What does this mean?
A: You are now a power user.

Story about 90-minute AI challenge.
Andy - "You're Fired"
Me - There is not credible eviddence that anyone ever learned anything helpful on "The Apprentice".


* Follow-up Note


** Curious and Collaborative

Hi – Your GenAI Day talk was insightful... especially as I look for my next step.  I STARTED as a dev...  GREW into helping teams thrive...  CURRENTLY exploring a blend: AI to develop products + AI to grow human skills.  Would love to trade thoughts.  Best, Michael



